version: "default"
focal_genes: ["MCR-1"]
complete: True
panx_export: False
bandage: False
snv_threshold: "25"
region_upstream: "5000"
region_downstream: "5000"
pangraph_polish: False
pangraph_aligner: "minimap2"
pangraph_seed: "0"
pangraph_alpha: "100"
pangraph_beta: "10"
pangraph_dist_backend: "native"
pangraph_minblocklength: "100"
pangraph_edgeminlength: "0"
include_gff: False
output_dir: "mcr1"
breakpoint_minimap2: False
