version: "default"
focal_genes : ["mcr-1.1"]
complete: True # incomplete is work-in-progress - don't use
panx_export : False
bandage : True
snv_threshold : "25"
region_upstream : "5000"
region_downstream : "5000"
pangraph_polish : False
pangraph_aligner : "minimap2"
pangraph_seed : 0 # random seed for pangraph
pangraph_alpha : 100 # alpha parameter, controls cost of splitting blocks
pangraph_beta : 10 # beta parameter, controls cost of block diversity
pangraph_minblocklength : "100" # minimum length of blocks 
pangraph_edgeminlength : "0"
DB: ["CARD"] # Can include "NCBI" if desired, but very similar results
include_gff: False
output_prefix : "output_example"
