version: "default"
focal_genes : ["IMP-4"]
complete: True # incomplete is work-in-progress - don't use
panx_export : False
bandage : True
snv_threshold : "25"
region_upstream : "5000"
region_downstream : "5000"
pangraph_polish : False
pangraph_aligner : "minimap2"
pangraph_seed : 0 # random seed for pangraph
pangraph_alpha : 100 # alpha parameter, controls cost of splitting blocks
pangraph_beta : 10 # beta parameter, controls cost of block diversity
pangraph_minblocklength : "100" # minimum length of blocks 
pangraph_edgeminlength : "0"
pangraph_dist_backend : "mash"
include_gff: False
output_dir : "output_example"
breakpoint_minimap2: False # whether to calculate breakpoint distances using minimap2 from full sequence (more accurate)
